# Generated by Django 2.0.9 on 2018-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knigi', '0002_auto_20181030_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sold_at',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(blank=True, through='knigi.Inventory', to='knigi.Book'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sold',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
